apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - {{ .Values.hosts.app }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.hosts.app }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: app
                port: 
                  number: 80
