apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 80
      name: app
    - port: 3000
      name: status
  selector:
    app: {{ ternary "app" "disabled" .Values.enabled }}
