{{- if eq .Values.parameterGroupsEnabled.postgres true }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
  selector:
    app: postgres
{{ end }}